name: fsi_maze_gen_find
description: Maze generate and find game for Fundamentals of Intelligent System
  class - Made By Gabriel Stabile, Isadora Fernandes and Amanda Faria.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  get: ^4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
